version: '3'

services:
  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "${PROJECT_PATH}/redis:/data"
    depends_on:
      - resolver
    dns:
      - 172.64.0.254

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:25:25"
      - "0.0.0.0:465:465"
      - "0.0.0.0:587:587"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
    volumes:
      - "${PROJECT_PATH}/certs:/certs"
      - "${PROJECT_PATH}/overrides/nginx:/overrides:ro"
      - "${PROJECT_PATH}/letsencrypt:/var/www/letsencrypt"
    depends_on:
      - resolver
    dns:
      - 172.64.0.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 172.64.0.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "${PROJECT_PATH}/data:/data"
      - "${PROJECT_PATH}/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 172.64.0.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "${PROJECT_PATH}/mail:/mail"
      - "${PROJECT_PATH}/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.64.0.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "${PROJECT_PATH}/mailqueue:/queue"
      - "${PROJECT_PATH}/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.64.0.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "${PROJECT_PATH}/filter:/var/lib/rspamd"
      - "${PROJECT_PATH}/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.64.0.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "${PROJECT_PATH}/filter:/data"
    depends_on:
      - resolver
    dns:
      - 172.64.0.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "${PROJECT_PATH}/webmail:/data"
      - "${PROJECT_PATH}/overrides/roundcube:/overrides:ro"
    depends_on:
      - imap
      - resolver
    dns:
      - 172.64.0.254

  ###########################################################################
  # Database
  ###########################################################################
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PW}"
    restart: always
    env_file: mailu.env
    expose:
      - "3306"
    volumes:
      - "${PROJECT_PATH}/mariadb:/var/lib/mysql"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.64.0.0/24

